Class {
	#name : #ManifestMooseOnWebRESTApiExceptions,
	#superclass : #Object,
	#category : #'MooseOnWeb-REST-Api-Exceptions'
}

{ #category : #'meta data' }
ManifestMooseOnWebRESTApiExceptions class >> rejectClasses [
^ #(#(#(#RGClassDefinition #(#MWRequestVisitor)) #'2013-07-26T15:24:54.244+02:00') #(#(#RGClassDefinition #(#MWEntitiesHandlerWithID)) #'2013-07-26T15:24:54.36+02:00') )
]

{ #category : #'meta data' }
ManifestMooseOnWebRESTApiExceptions class >> rejectRules [
^ #()
]
