Class {
	#name : #MWRequestASTVisitor,
	#superclass : #Object,
	#category : #'MooseOnWeb-Request-ASTVisitor'
}

{ #category : #visit }
MWRequestASTVisitor >> visitMWRequestNodeAnd: aMWRequestNodeAnd [
	self shouldBeImplemented
]

{ #category : #visit }
MWRequestASTVisitor >> visitMWRequestNodeCondition: aMWRequestNodeCondition [
	self shouldBeImplemented
]

{ #category : #visit }
MWRequestASTVisitor >> visitMWRequestNodeNot: aMWRequestNodeNot [
	self shouldBeImplemented
]

{ #category : #visit }
MWRequestASTVisitor >> visitMWRequestNodeOr: aMWRequestNodeOr [
	self shouldBeImplemented
]
