Class {
	#name : #ManifestMooseOnWebRESTApiTests,
	#superclass : #Object,
	#category : #'MooseOnWeb-REST-Api-Tests'
}

{ #category : #'meta data' }
ManifestMooseOnWebRESTApiTests class >> rejectClasses [
^ #(#(#(#RGClassDefinition #(#MWRequestVisitor)) #'2013-07-26T15:24:52.974+02:00') #(#(#RGClassDefinition #(#MWEntitiesHandlerWithID)) #'2013-07-26T15:24:53.096+02:00') )
]

{ #category : #'meta data' }
ManifestMooseOnWebRESTApiTests class >> rejectRules [
^ #()
]
