Class {
	#name : #ManifestMooseOnWebRESTApiGrammarAST,
	#superclass : #Object,
	#category : #'MooseOnWeb-REST-Api-Grammar-AST'
}

{ #category : #'meta data' }
ManifestMooseOnWebRESTApiGrammarAST class >> rejectClasses [
^ #(#(#(#RGClassDefinition #(#MWRequestVisitor)) #'2013-07-26T15:24:53.49+02:00') #(#(#RGClassDefinition #(#MWEntitiesHandlerWithID)) #'2013-07-26T15:24:53.61+02:00') )
]

{ #category : #'meta data' }
ManifestMooseOnWebRESTApiGrammarAST class >> rejectRules [
^ #()
]
